export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).send('gg.alert("❌ Method Not Allowed.")');
  }

  const { key, pkg } = req.body;

  if (key !== process.env.ADMIN_KEY || pkg !== "com.mobile.legends") {
    return res.status(401).send('gg.alert("❌ Unauthorized Access!")');
  }

  const EXPIRY = parseInt(process.env.EXPIRY_TIMESTAMP) || 1800000000;
  const now = Math.floor(Date.now() / 1000);
  if (now > EXPIRY) {
    return res.status(403).send('gg.alert("⚠️ [ SUBSCRIPTION EXPIRED ] ⚠️")');
  }

  const response = await fetch(`https://raw.githubusercontent.com/Jking123456/mlbb-maphack-drone/main/main.lua`, {
    headers: { 'Authorization': `token ${process.env.GITHUB_TOKEN}` }
  });

  if (response.ok) {
    let rawScript = await response.text();

    // 🛡️ ANTI-TAMPER: Fingerprint Check
    let checksum = 0;
    for (let i = 0; i < rawScript.length; i++) {
        checksum = (checksum + rawScript.charCodeAt(i) * (i + 1)) % 9999999;
    }
    
    // Set SCRIPT_FINGERPRINT in Vercel to the number generated by your encryptor
    if (process.env.SCRIPT_FINGERPRINT && checksum.toString() !== process.env.SCRIPT_FINGERPRINT) {
        return res.status(403).send('gg.alert("❌ TAMPER DETECTED!\\n\\nThe script file on GitHub has been modified illegally.");os.exit()');
    }

    const notice = process.env.ADMIN_NOTICE || "";
    let noticeInject = notice !== "" ? `gg.alert("📢 [ ADMIN ANNOUNCEMENT ] 📢\\n\\n${notice}");\n` : "";
    
    const diff = EXPIRY - now;
    const timeStr = `🕒 Expire: ${Math.floor(diff / 3600)}h ${Math.floor((diff % 3600) / 60)}m`;
    const injection = `_G.time_left = "${timeStr}";\n_G.mh_v = ${process.env.MAPHACK_VALUE};\n_G.dr_p = ${process.env.DRONE_DATA_JSON};\n\n`;

    const finalScript = noticeInject + injection + rawScript;

    const KEY_A = "ClientPart_99"; 
    const KEY_B = process.env.XOR_KEY_B || "ServerPart_77"; 
    const dataBuf = Buffer.from(finalScript);
    const keyBuf = Buffer.from(KEY_A + KEY_B);
    
    let encryptedArray = [];
    for (let i = 0; i < dataBuf.length; i++) {
      encryptedArray.push(dataBuf[i] ^ keyBuf[i % keyBuf.length]);
    }

    res.setHeader('X-Session-Token', KEY_B);
    res.status(200).send(encryptedArray.join(",")); 
  } else {
    res.status(500).send('gg.alert("❌ GitHub Sync Failed")');
  }
}

